//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkyIndexAnalyzerSolo.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,9")]
        public string GrIxDefaultSkyCloudMarginWithoutSun {
            get {
                return ((string)(this["GrIxDefaultSkyCloudMarginWithoutSun"]));
            }
            set {
                this["GrIxDefaultSkyCloudMarginWithoutSun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,1")]
        public string GrIxDefaultSkyCloudMarginWithSun {
            get {
                return ((string)(this["GrIxDefaultSkyCloudMarginWithSun"]));
            }
            set {
                this["GrIxDefaultSkyCloudMarginWithSun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,003")]
        public string GrIxSunDetectionMinimalSunAreaPartial {
            get {
                return ((string)(this["GrIxSunDetectionMinimalSunAreaPartial"]));
            }
            set {
                this["GrIxSunDetectionMinimalSunAreaPartial"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,05")]
        public string GrIxSunDetectionMaximalSunAreaPartial {
            get {
                return ((string)(this["GrIxSunDetectionMaximalSunAreaPartial"]));
            }
            set {
                this["GrIxSunDetectionMaximalSunAreaPartial"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,9")]
        public string GrIxAnalysisImageCircledCropFactor {
            get {
                return ((string)(this["GrIxAnalysisImageCircledCropFactor"]));
            }
            set {
                this["GrIxAnalysisImageCircledCropFactor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,1")]
        public string JapanCloudSkySeparationValue {
            get {
                return ((string)(this["JapanCloudSkySeparationValue"]));
            }
            set {
                this["JapanCloudSkySeparationValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,8")]
        public string GermanCloudSkySeparationValue {
            get {
                return ((string)(this["GermanCloudSkySeparationValue"]));
            }
            set {
                this["GermanCloudSkySeparationValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,65")]
        public string GrIxStdDevMarginValueDefiningTrueSkyArea {
            get {
                return ((string)(this["GrIxStdDevMarginValueDefiningTrueSkyArea"]));
            }
            set {
                this["GrIxStdDevMarginValueDefiningTrueSkyArea"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("G:\\_gulevlab\\SkyIndexAnalyzerSolo_appData\\2014-03-MassiveProcessingResult\\images\\" +
            "")]
        public string BatchProcessingDirectory {
            get {
                return ((string)(this["BatchProcessingDirectory"]));
            }
            set {
                this["BatchProcessingDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("G:\\_gulevlab\\SkyIndexAnalyzerSolo_appData\\2014-03-MassiveProcessingResult\\")]
        public string DefaultDataFilesLocation {
            get {
                return ((string)(this["DefaultDataFilesLocation"]));
            }
            set {
                this["DefaultDataFilesLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,125")]
        public string DefaultScalingFactor {
            get {
                return ((string)(this["DefaultScalingFactor"]));
            }
            set {
                this["DefaultScalingFactor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public string GrIxProcessingVerbosityLevel {
            get {
                return ((string)(this["GrIxProcessingVerbosityLevel"]));
            }
            set {
                this["GrIxProcessingVerbosityLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("512")]
        public string DefaultMaxImageSize {
            get {
                return ((string)(this["DefaultMaxImageSize"]));
            }
            set {
                this["DefaultMaxImageSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,01")]
        public string GrIxSunDetectionDesiredSunAreaPartial {
            get {
                return ((string)(this["GrIxSunDetectionDesiredSunAreaPartial"]));
            }
            set {
                this["GrIxSunDetectionDesiredSunAreaPartial"] = value;
            }
        }
    }
}
