//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilesFilteringApp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\_gulevlab\\SkyImagesAnalysis_appData\\AI45-total\\ID1\\")]
        public string FromPath {
            get {
                return ((string)(this["FromPath"]));
            }
            set {
                this["FromPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\_gulevlab\\SkyImagesAnalysis_appData\\AI45-with-concurrent-data\\input\\")]
        public string ToPath {
            get {
                return ((string)(this["ToPath"]));
            }
            set {
                this["ToPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\_gulevlab\\SkyImagesAnalysis_appData\\AI45-total\\ID1\\concurrentdata\\")]
        public string FromConcurrentPath {
            get {
                return ((string)(this["FromConcurrentPath"]));
            }
            set {
                this["FromConcurrentPath"] = value;
            }
        }
    }
}
